name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unit tests
        run: |
          export BASE_URL=https://scicat.ess.eu/api/v3
          npm ci
          npm test

  gitlab:
    name: Build and deploy
    needs: [test]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ESS pipeline
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.TOKEN }}
          project_id: 2938
          ref: 'master'
          host: 'https://gitlab.esss.lu.se'
          debug: true

      - name: Trigger MAXIV pipeline
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.MAXIV_TOKEN }}
          project_id: 22103219
          ref: 'master'
          host: 'https://gitlab.com'
          debug: true
