name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger Job
        uses: appleboy/gitlab-ci-action@master
        with:
          url: 'https://gitlab.esss.lu.se/api/v4/projects/2938/trigger/pipeline'
          token: ${{ secrets.TOKEN }}
          project_id: 2938
          ref: 'master'
          host: 'https://gitlab.esss.lu.se'
          debug: true

      - name: trigger MAXIV Job
        uses: appleboy/gitlab-ci-action@master
        with:
          url: 'https://gitlab.com/api/v4/projects/22103219/trigger/pipeline'
          token: ${{ secrets.MAXIV_TOKEN }}
          project_id: 22103219
          ref: 'master'
          host: 'https://gitlab.com'
          debug: true
